# Generated by Django 3.2.5 on 2021-08-02 01:17

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Packs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='عنوان')),
                ('weight', models.PositiveIntegerField(blank=True, null=True, verbose_name='اندازه')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.packs', verbose_name='نوع')),
            ],
            options={
                'verbose_name': 'بسته',
                'verbose_name_plural': 'بسته ها',
            },
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام کالا')),
                ('slug', models.SlugField(allow_unicode=True, max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('inventory', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='موجودی')),
                ('available', models.BooleanField(default=True, verbose_name='(موجودی)وضعیت')),
                ('sell', models.IntegerField(default=0, verbose_name='تعداد فروش')),
                ('show_cost', models.IntegerField(default=0, verbose_name='قیمت نمایشی')),
            ],
            options={
                'verbose_name': 'کالا',
                'verbose_name_plural': 'کالا ها',
            },
        ),
        migrations.CreateModel(
            name='ProductGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='product/', verbose_name='عکس')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='picture', to='product.product')),
            ],
            options={
                'verbose_name': 'عکس ',
                'verbose_name_plural': 'عکس ها',
            },
        ),
        migrations.CreateModel(
            name='product_group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='متن نمایشی', max_length=100, null=True, verbose_name='متن')),
                ('slug', models.SlugField(allow_unicode=True, max_length=255, unique=True)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='product_group/', verbose_name='عکس')),
                ('group', models.ForeignKey(blank=True, help_text='درصورت داشتن سر گروه ، وارد شود ', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_group', to='product.product_group', verbose_name='سر گروه')),
            ],
            options={
                'verbose_name': 'دسته بندی',
                'verbose_name_plural': 'دسته بندی ها',
                'unique_together': {('slug', 'name')},
            },
        ),
        migrations.AddField(
            model_name='product',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='product.product_group', verbose_name='گروه'),
        ),
        migrations.CreateModel(
            name='comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=False)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.comment')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'نظر',
                'verbose_name_plural': 'نظرات',
            },
        ),
        migrations.CreateModel(
            name='Product_Cost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(99)], verbose_name='تخفیف')),
                ('cost', models.IntegerField(verbose_name='قیمت')),
                ('available', models.BooleanField(default=True, verbose_name='(بسته)وضعیت')),
                ('pack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_cost', to='product.packs', verbose_name='بسته')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_cost', to='product.product', verbose_name='کالا')),
            ],
            options={
                'verbose_name': 'قیمت',
                'verbose_name_plural': 'قیمت ها',
                'unique_together': {('product', 'pack')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('slug', 'name')},
        ),
    ]
