# Generated by Django 3.2.5 on 2021-08-02 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='productgallery',
            name='active',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
