# Generated by Django 3.2.5 on 2021-08-18 03:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel_accounting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='journal2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('debtor', models.IntegerField()),
                ('creditor', models.IntegerField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journals', to='admin_panel_accounting.account')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journals', to='admin_panel_accounting.document')),
            ],
        ),
    ]
