# Generated by Django 3.2.5 on 2021-08-15 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel_accounting', '0004_auto_20210815_0730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='creditor',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='journal',
            name='debtor',
            field=models.IntegerField(),
        ),
    ]
