# Generated by Django 3.2.5 on 2021-08-17 21:08

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel_accounting', '0005_auto_20210815_0742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='date',
            field=django_jalali.db.models.jDateField(),
        ),
    ]
