# Generated by Django 3.2.5 on 2021-08-12 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accounting_Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Accounts_Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='نام حساب')),
                ('type', models.IntegerField(choices=[(1, 'اشخاص'), (2, 'مواد اولیه'), (3, 'محصول')], verbose_name='نوع حساب')),
            ],
        ),
        migrations.CreateModel(
            name='Accounting_Score_Rows',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='شرح')),
                ('debit', models.IntegerField(verbose_name='بدهکار')),
                ('credit', models.IntegerField(verbose_name='بستانکار')),
                ('accounting_score', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounting_score_rows', to='admin_panel.accounting_score')),
                ('accounts_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounting_score_rows', to='admin_panel.accounts_form')),
            ],
        ),
    ]
