# Generated by Django 3.2.5 on 2021-08-02 00:54

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='image_section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_img', models.ImageField(blank=True, help_text='عکس برای صفحه لاگین ', null=True, upload_to='login_img/', verbose_name='login')),
                ('register_img', models.ImageField(blank=True, help_text='عکس برای صفحه ثبت نام ', null=True, upload_to='register_img/', verbose_name='register')),
                ('re_password_img', models.ImageField(blank=True, help_text='عکس برای صفحه فراموشی رمز ', null=True, upload_to='re_password_img/', verbose_name='re password')),
            ],
            options={
                'verbose_name': 'تصویر',
                'verbose_name_plural': 'تصاویر',
            },
        ),
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=11, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '09176666666'. Up to 11 digits allowed.", regex='((\\+|00)98|0)9\\d{9}')])),
                ('money', models.IntegerField(default=0, verbose_name='money')),
                ('registration_date', models.DateField(auto_now_add=True, verbose_name='registration date')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='users_picture/', verbose_name='picture')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'کاربر',
                'verbose_name_plural': 'کاربران',
            },
        ),
    ]
