# Generated by Django 3.2.5 on 2021-08-20 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='accessibility',
            field=models.CharField(choices=[('0', 'عادی'), ('1', 'سطح یک'), ('2', 'سطح دو'), ('3', 'سطح سه')], default='0', max_length=100),
        ),
    ]
