# Generated by Django 3.2.5 on 2021-08-03 21:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, choices=[('1', 'پیشنهاد'), ('2', 'انتقاد یا شکایت'), ('3', 'مدیریت'), ('4', 'حسابداری'), ('5', 'سایر موضوعات')], max_length=100, null=True, verbose_name='عنوان')),
                ('status', models.CharField(choices=[('1', 'باز'), ('2', 'بسته')], default=1, max_length=100, verbose_name='وضعیت')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='تاریخ تشکیل مکالمه ')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'مکالمه های پشتیبانی ',
                'verbose_name_plural': 'مکالمه',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('date', models.DateTimeField(auto_now=True, verbose_name='تاریخ تشکیل مکالمه ')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='support.conversation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'پیام های مکالمه پشتیبانی ',
                'verbose_name_plural': 'پیام',
                'ordering': ['-date'],
            },
        ),
    ]
