# Generated by Django 3.2.5 on 2021-08-03 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, choices=[('1', 'پیشنهاد'), ('2', 'انتقاد یا شکایت'), ('3', 'مدیریت'), ('4', 'حسابداری'), ('5', 'سایر موضوعات')], max_length=100, null=True, verbose_name='عنوان')),
                ('status', models.CharField(choices=[('1', 'باز'), ('2', 'بسته')], default=1, max_length=100, verbose_name='وضعیت')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='تاریخ تشکیل مکالمه ')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.users')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('date', models.DateTimeField(auto_now=True, verbose_name='تاریخ تشکیل مکالمه ')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='support.conversation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.users')),
            ],
        ),
    ]
