# Generated by Django 3.2.5 on 2021-08-02 01:35

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About_Us',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='سر تیتر')),
                ('sub_title', models.CharField(blank=True, max_length=100, null=True, verbose_name='توضیح کوتاه')),
                ('body', models.TextField(blank=True, null=True, verbose_name='متن')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='About_Us/', verbose_name='عکس')),
            ],
            options={
                'verbose_name': 'دربارهی ما',
                'verbose_name_plural': 'درباره ی ما',
            },
        ),
        migrations.CreateModel(
            name='Contact_Us',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, choices=[('1', 'پیشنهاد'), ('2', 'انتقاد یا شکایت'), ('3', 'مدیریت'), ('4', 'حسابداری'), ('5', 'سایر موضوعات')], max_length=100, null=True, verbose_name='عنوان')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='نام')),
                ('email', models.EmailField(blank=True, max_length=100, null=True, verbose_name='ایمیل')),
                ('phone', models.CharField(blank=True, max_length=11, null=True, verbose_name='شماره تماس')),
                ('body', models.TextField(blank=True, null=True, verbose_name='متن')),
            ],
            options={
                'verbose_name': 'ارتباط با ما',
                'verbose_name_plural': 'ارتباط با ما',
            },
        ),
        migrations.CreateModel(
            name='FAQ_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='عنوان')),
                ('body', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='متن')),
            ],
            options={
                'verbose_name': 'سوالات متداول',
                'verbose_name_plural': 'سوالات',
            },
        ),
        migrations.CreateModel(
            name='Private_Site_Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='نام سایت')),
                ('motto', models.TextField(blank=True, null=True, verbose_name='شعار')),
                ('phone', models.CharField(blank=True, max_length=11, null=True, verbose_name='تلفون سایت')),
                ('email', models.EmailField(blank=True, max_length=100, null=True, verbose_name='ایمیل سایت')),
                ('telegram_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='آدرس تلگرام سایت')),
                ('instagram_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='آدرس اینستاگرام سایت')),
                ('whatsapp_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='آدرس واتس آپ سایت')),
                ('main_img_1', models.ImageField(blank=True, null=True, upload_to='main_site/', verbose_name='عکس')),
                ('main_img_2', models.ImageField(blank=True, null=True, upload_to='main_site/', verbose_name='عکس')),
                ('product_img_1', models.ImageField(blank=True, null=True, upload_to='main_site/', verbose_name='عکس')),
                ('product_img_2', models.ImageField(blank=True, null=True, upload_to='main_site/', verbose_name='عکس')),
                ('product_img_3', models.ImageField(blank=True, null=True, upload_to='main_site/', verbose_name='عکس')),
                ('title_1', models.CharField(blank=True, max_length=100, null=True, verbose_name='سر تیتر')),
                ('body_1', models.TextField(blank=True, null=True, verbose_name='متن')),
                ('title_2', models.CharField(blank=True, max_length=100, null=True, verbose_name='سر تیتر')),
                ('body_2', models.TextField(blank=True, null=True, verbose_name='متن')),
            ],
            options={
                'verbose_name': 'اطلاعات',
                'verbose_name_plural': 'اطلاعات',
            },
        ),
    ]
