# Generated by Django 3.2.5 on 2021-08-13 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_model', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Site_Information_Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='main_site/gallery/', verbose_name='عکس')),
            ],
            options={
                'verbose_name': 'عکس ',
                'verbose_name_plural': 'عکس ها',
            },
        ),
        migrations.RemoveField(
            model_name='private_site_information',
            name='main_img_1',
        ),
        migrations.RemoveField(
            model_name='private_site_information',
            name='main_img_2',
        ),
    ]
