# Generated by Django 3.2.5 on 2021-08-25 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_model', '0003_bugs'),
    ]

    operations = [
        migrations.AddField(
            model_name='private_site_information',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logo/', verbose_name='عکس'),
        ),
        migrations.AddField(
            model_name='private_site_information',
            name='sign_one',
            field=models.ImageField(blank=True, null=True, upload_to='sign/', verbose_name='عکس'),
        ),
        migrations.AddField(
            model_name='private_site_information',
            name='sign_two',
            field=models.ImageField(blank=True, null=True, upload_to='sign/', verbose_name='عکس'),
        ),
    ]
